name: pcl
channels:
  - conda-forge
  - defaults
  - ccordoba12
dependencies:
  - python=2.7
  - numpy
  - matplotlib
  - pandas
  - notebook
  - ipywidgets
  - ipython
  - python-pcl
  - pcl
  - pip:
    - appmode
