name: pcl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - notebook>=5.2.2
  - ipywidgets>=6.0.1
  - ipython>=6.2.1
  - pcl
  - pip:
    - appmode
    - cython==0.25.2
